### ISSUE TITLE
[Ws] ObjID 3388 indicates missing Ws unit 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/trial#87]
Branch: jpc-test
ObjID 3380, Resource:910
Unit: "Ws" 

This unit is present in the the branch "jpc-test" in the file "lwm2m-senml-units" however an error is raised.

Which is the reference "lwm2m2-senml-units" file used for this validation?

**Comment by SvanteAlnas** [comment]
This is expected behavior. Units are only validated with the pre-configured SenML unit file. The "Validate Branch" feature exclude non xml files and the SenML file, it does not use it.

**Comment by jpradocueva** [comment]
It is working ok.
When using the web interface it is necessary to tick the box. When validating a repo or via GitHub the tool includes the validation of "senml-units' file by detault.
